# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ServiceNow.Core
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: yarn --cwd ./ServiceNoe.Core
    - run: yarn docs:build --if-present
    - run: ls -la
    - name: Publish generated content to GitHub Pages    
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
          dir: ServiceNow.Core/Docs/.vitepress/dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
    - run: ls -la
    #- run: ./deploy.sh
    #  shell: bash
